export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const DISPLAY_RESULTS = 'DISPLAY_RESULTS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';